import { Task } from "../task.js";
import type {
  AIHTTPHeaders,
  TaskResult,
  WorkflowContext,
  WorkflowDefinition,
  WorkflowMemory
} from "../types.js";

function toInputText(input: unknown): string {
  if (typeof input === "string") {
    return input;
  }

  return JSON.stringify(input, null, 2);
}

function resolveRequestHeaders(input: unknown): AIHTTPHeaders | undefined {
  if (!input || typeof input !== "object" || !("requestHeaders" in input)) {
    return undefined;
  }

  const requestHeaders = input.requestHeaders;
  if (!requestHeaders || typeof requestHeaders !== "object" || Array.isArray(requestHeaders)) {
    return undefined;
  }

  const headers: AIHTTPHeaders = {};

  for (const [key, value] of Object.entries(requestHeaders)) {
    if (typeof value === "string") {
      headers[key] = value;
    }
  }

  return Object.keys(headers).length > 0 ? headers : undefined;
}

class StreamSummaryTask extends Task {
  name = "streamSummary";
  memoryPhase = "EXECUTION" as const;
  memoryTaskType = "workflow" as const;

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const sourceText = toInputText(ctx.input);
    const requestHeaders = resolveRequestHeaders(ctx.input);
    ctx.log.info("Starting streaming AI chat completion", {
      model: ctx.session.llmModelId,
      hasRequestHeaders: requestHeaders !== undefined
    });

    const stream = await ctx.ai.chatStream({
      messages: [
        {
          role: "developer",
          content:
            "You stream a concise operational summary for an AX Workflow run using direct wording."
        },
        {
          role: "user",
          content: `Summarize the following input for an AX Workflow run:\n\n${sourceText}\n\nRetrieved context:\n${ctx.memoryContext?.assembledContext ?? "none"}`
        }
      ],
      ...(requestHeaders
        ? {
            http: {
              headers: requestHeaders
            }
          }
        : {})
    });

    for await (const chunk of stream) {
      if (chunk.deltaText) {
        ctx.log.info("Received streaming chunk", {
          deltaLength: chunk.deltaText.length,
          outputLength: chunk.outputText.length
        });
      }
    }

    const completion = await stream.finalResponse;
    const summaryRecordId = `memory.workflow.summary.${ctx.workflowId}.streamSummary`;
    await ctx.memory.write({
      id: summaryRecordId,
      shard: "workflow",
      kind: "summary",
      payload: {
        workflowId: ctx.workflowId,
        currentStep: this.name,
        history: [],
        contextSummary: completion.outputText
      } satisfies WorkflowMemory,
      description: "Summary generated by AI chat provider via streaming",
      keywords: ["summary", "ai", "chat", "stream"],
      importance: 0.92,
      workflowId: ctx.workflowId,
      runId: ctx.runId,
      sourceTask: this.name,
      phase: this.memoryPhase,
      taskType: this.memoryTaskType
    });

    ctx.log.success("Stored streaming AI summary", {
      provider: completion.provider,
      model: completion.model
    });

    return {
      status: "success",
      output: {
        summaryRecordId,
        summary: completion.outputText,
        model: completion.model,
        provider: completion.provider
      }
    };
  }
}

class PublishStreamingSummaryTask extends Task {
  name = "publishStreamingSummary";
  memoryPhase = "REFLECTION" as const;
  memoryTaskType = "workflow" as const;

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const summaryRecord = await ctx.memory.get(
      `memory.workflow.summary.${ctx.workflowId}.streamSummary`,
    );
    const summary = summaryRecord && "contextSummary" in summaryRecord.payload
      ? summaryRecord.payload.contextSummary
      : "No summary";

    const artifact = await ctx.artifacts.create({
      name: "ai-stream-summary.md",
      mimeType: "text/markdown",
      bytes: new TextEncoder().encode(`# AI Streaming Summary\n\n${summary}\n`),
      meta: {
        task: this.name
      }
    });

    ctx.log.success("Created AI streaming summary artifact", {
      artifactId: artifact.artifactId
    });

    return {
      status: "success",
      output: artifact
    };
  }
}

export const OpenAIStreamingSummaryWorkflow: WorkflowDefinition = {
  name: "openai-streaming-summary",
  start: "streamSummary",
  end: "end",
  tasks: {
    streamSummary: new StreamSummaryTask(),
    publishStreamingSummary: new PublishStreamingSummaryTask()
  },
  transitions: {
    streamSummary: {
      success: "publishStreamingSummary",
      fail: "end"
    },
    publishStreamingSummary: {
      success: "end",
      fail: "end"
    }
  }
};
