import { Task } from "../task.js";
import type {
  TaskResult,
  WorkflowContext,
  WorkflowDefinition,
  WorkflowMemory
} from "../types.js";
import { workflowInputToPrettyJson } from "../workflow-input.js";

function toInputText(input: WorkflowContext["input"]): string {
  return workflowInputToPrettyJson(input);
}

class GenerateSummaryTask extends Task {
  name = "generateSummary";
  memoryPhase = "EXECUTION" as const;
  memoryTaskType = "workflow" as const;

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const sourceText = toInputText(ctx.input);
    ctx.log.info("Calling AI chat completion", {
      model: ctx.session.llmModelId
    });

    const completion = await ctx.ai.chat({
      messages: [
        {
          role: "developer",
          content:
            "You summarize workflow inputs into a short execution brief with direct, operational wording."
        },
        {
          role: "user",
          content: `Summarize the following input for an AX Workflow run:\n\n${sourceText}\n\nRetrieved context:\n${ctx.memoryContext?.assembledContext ?? "none"}`
        }
      ]
    });

    const summaryRecordId = `memory.workflow.summary.${ctx.workflowId}.generateSummary`;
    await ctx.memory.write({
      id: summaryRecordId,
      shard: "workflow",
      kind: "summary",
      payload: {
        workflowId: ctx.workflowId,
        currentStep: this.name,
        history: [],
        contextSummary: completion.outputText
      } satisfies WorkflowMemory,
      description: "Summary generated by AI chat provider",
      keywords: ["summary", "ai", "chat"],
      importance: 0.92,
      workflowId: ctx.workflowId,
      runId: ctx.runId,
      sourceTask: this.name,
      phase: this.memoryPhase,
      taskType: this.memoryTaskType
    });
    ctx.log.success("Stored AI summary", {
      provider: completion.provider,
      model: completion.model
    });

    return {
      status: "success",
      output: {
        summaryRecordId,
        summary: completion.outputText,
        model: completion.model,
        provider: completion.provider
      }
    };
  }
}

class PublishAISummaryTask extends Task {
  name = "publishSummary";
  memoryPhase = "REFLECTION" as const;
  memoryTaskType = "workflow" as const;

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const summaryRecord = await ctx.memory.get(
      `memory.workflow.summary.${ctx.workflowId}.generateSummary`,
    );
    const summary = summaryRecord && "contextSummary" in summaryRecord.payload
      ? summaryRecord.payload.contextSummary
      : "No summary";

    const artifact = await ctx.artifacts.create({
      name: "ai-summary.md",
      mimeType: "text/markdown",
      bytes: new TextEncoder().encode(`# AI Summary\n\n${summary}\n`),
      meta: {
        task: this.name
      }
    });

    ctx.log.success("Created AI summary artifact", {
      artifactId: artifact.artifactId
    });

    return {
      status: "success",
      output: artifact
    };
  }
}

export const OpenAISummaryWorkflow: WorkflowDefinition = {
  name: "openai-summary",
  start: "generateSummary",
  end: "end",
  tasks: {
    generateSummary: new GenerateSummaryTask(),
    publishSummary: new PublishAISummaryTask()
  },
  transitions: {
    generateSummary: {
      success: "publishSummary",
      fail: "end"
    },
    publishSummary: {
      success: "end",
      fail: "end"
    }
  }
};
