import { Task } from "../task.js";
import type {
  AIHTTPHeaders,
  MemoryPiece,
  TaskResult,
  WorkflowContext,
  WorkflowDefinition
} from "../types.js";

function toInputText(input: unknown): string {
  if (typeof input === "string") {
    return input;
  }

  return JSON.stringify(input, null, 2);
}

function resolveRequestHeaders(input: unknown): AIHTTPHeaders | undefined {
  if (!input || typeof input !== "object" || !("requestHeaders" in input)) {
    return undefined;
  }

  const requestHeaders = input.requestHeaders;
  if (!requestHeaders || typeof requestHeaders !== "object" || Array.isArray(requestHeaders)) {
    return undefined;
  }

  const headers: AIHTTPHeaders = {};

  for (const [key, value] of Object.entries(requestHeaders)) {
    if (typeof value === "string") {
      headers[key] = value;
    }
  }

  return Object.keys(headers).length > 0 ? headers : undefined;
}

class StreamSummaryTask extends Task {
  name = "streamSummary";

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const sourceText = toInputText(ctx.input);
    const requestHeaders = resolveRequestHeaders(ctx.input);
    ctx.log.info("Starting streaming AI chat completion", {
      model: ctx.session.llmModelId,
      hasRequestHeaders: requestHeaders !== undefined
    });

    const stream = await ctx.ai.chatStream({
      messages: [
        {
          role: "developer",
          content:
            "You stream a concise operational summary for an AX Workflow run using direct wording."
        },
        {
          role: "user",
          content: `Summarize the following input for an AX Workflow run:\n\n${sourceText}`
        }
      ],
      ...(requestHeaders
        ? {
            http: {
              headers: requestHeaders
            }
          }
        : {})
    });

    for await (const chunk of stream) {
      if (chunk.deltaText) {
        ctx.log.info("Received streaming chunk", {
          deltaLength: chunk.deltaText.length,
          outputLength: chunk.outputText.length
        });
      }
    }

    const completion = await stream.finalResponse;
    const summaryPiece: MemoryPiece = {
      key: `workflow.${ctx.workflowId}.task.streamSummary.summary`,
      scope: "workflow",
      category: "summary",
      description: "Summary generated by AI chat provider via streaming",
      keywords: ["summary", "ai", "chat", "stream"],
      value: {
        summary: completion.outputText,
        model: completion.model,
        provider: completion.provider
      },
      importance: 0.9,
      createdAt: ctx.now(),
      updatedAt: ctx.now(),
      sourceTask: this.name
    };

    await ctx.memory.put(summaryPiece);
    ctx.log.success("Stored streaming AI summary", {
      provider: completion.provider,
      model: completion.model
    });

    return {
      status: "success",
      output: summaryPiece.value
    };
  }
}

class PublishStreamingSummaryTask extends Task {
  name = "publishStreamingSummary";

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const summaryPiece = await ctx.memory.get(
      `workflow.${ctx.workflowId}.task.streamSummary.summary`
    );
    const summary = (summaryPiece?.value as { summary?: string } | undefined)?.summary ?? "No summary";

    const artifact = await ctx.artifacts.create({
      name: "ai-stream-summary.md",
      mimeType: "text/markdown",
      bytes: new TextEncoder().encode(`# AI Streaming Summary\n\n${summary}\n`),
      meta: {
        task: this.name
      }
    });

    ctx.log.success("Created AI streaming summary artifact", {
      artifactId: artifact.artifactId
    });

    return {
      status: "success",
      output: artifact
    };
  }
}

export const OpenAIStreamingSummaryWorkflow: WorkflowDefinition = {
  name: "openai-streaming-summary",
  start: "streamSummary",
  end: "end",
  tasks: {
    streamSummary: new StreamSummaryTask(),
    publishStreamingSummary: new PublishStreamingSummaryTask()
  },
  transitions: {
    streamSummary: {
      success: "publishStreamingSummary",
      fail: "end"
    },
    publishStreamingSummary: {
      success: "end",
      fail: "end"
    }
  }
};
