import { Task } from "../task.js";
import type {
  MemoryPiece,
  TaskResult,
  WorkflowContext,
  WorkflowDefinition
} from "../types.js";

function toInputText(input: unknown): string {
  if (typeof input === "string") {
    return input;
  }

  return JSON.stringify(input, null, 2);
}

class GenerateSummaryTask extends Task {
  name = "generateSummary";

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const sourceText = toInputText(ctx.input);
    ctx.log.info("Calling AI chat completion", {
      model: ctx.session.llmModelId
    });

    const completion = await ctx.ai.chat({
      messages: [
        {
          role: "developer",
          content:
            "You summarize workflow inputs into a short execution brief with direct, operational wording."
        },
        {
          role: "user",
          content: `Summarize the following input for an AX Workflow run:\n\n${sourceText}`
        }
      ]
    });

    const summaryPiece: MemoryPiece = {
      key: `workflow.${ctx.workflowId}.task.generateSummary.summary`,
      scope: "workflow",
      category: "summary",
      description: "Summary generated by AI chat provider",
      keywords: ["summary", "ai", "chat"],
      value: {
        summary: completion.outputText,
        model: completion.model,
        provider: completion.provider
      },
      importance: 0.9,
      createdAt: ctx.now(),
      updatedAt: ctx.now(),
      sourceTask: this.name
    };

    await ctx.memory.put(summaryPiece);
    ctx.log.success("Stored AI summary", {
      provider: completion.provider,
      model: completion.model
    });

    return {
      status: "success",
      output: summaryPiece.value
    };
  }
}

class PublishAISummaryTask extends Task {
  name = "publishSummary";

  async run(ctx: WorkflowContext): Promise<TaskResult> {
    const summaryPiece = await ctx.memory.get(
      `workflow.${ctx.workflowId}.task.generateSummary.summary`
    );
    const summary = (summaryPiece?.value as { summary?: string } | undefined)?.summary ?? "No summary";

    const artifact = await ctx.artifacts.create({
      name: "ai-summary.md",
      mimeType: "text/markdown",
      bytes: new TextEncoder().encode(`# AI Summary\n\n${summary}\n`),
      meta: {
        task: this.name
      }
    });

    ctx.log.success("Created AI summary artifact", {
      artifactId: artifact.artifactId
    });

    return {
      status: "success",
      output: artifact
    };
  }
}

export const OpenAISummaryWorkflow: WorkflowDefinition = {
  name: "openai-summary",
  start: "generateSummary",
  end: "end",
  tasks: {
    generateSummary: new GenerateSummaryTask(),
    publishSummary: new PublishAISummaryTask()
  },
  transitions: {
    generateSummary: {
      success: "publishSummary",
      fail: "end"
    },
    publishSummary: {
      success: "end",
      fail: "end"
    }
  }
};
